# Generated by Django 5.2.8 on 2025-11-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
